### ISSUE TITLE
build breakage in osx

### ISSUE THREAD

**Issue by nickdesaulniers** [mongrel2/mongrel2#200]
OSX 10.8.5

Kept getting strange errors linking against the std C++ lib:

```
cc -g -O2 -Wall -Wextra -Isrc -pthread -rdynamic -DNDEBUG  -D_FILE_OFFSET_BITS=64 src/mongrel2.o -o bin/mongrel2 build/libm2.a -lzmq -ldl -lsqlite3 -stdlib=libstdc++
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "std::string::find(char const*, unsigned long) const", referenced from:
      zmq::socket_base_t::parse_uri(char const*, std::string&, std::string&) in libzmq.a(libzmq_la-socket_base.o)
  "std::string::size() const", referenced from:
...
```

Looking into it, there [appears](http://stackoverflow.com/a/19637199/1027966) to be [two different](http://mathematica.stackexchange.com/a/34773) implementations of the c++ std lib in OSX?  I don't know much about C++ programming, but adding a new build target helped out (PR inbound).  Not sure if that's the correct solution, but we can work it out in the PR.  Big fan of your work, btw.

**Comment by jasom** [comment]
I was unable to reproduce this
