### ISSUE TITLE
Mongrel2 doesn't support HTTP versions higher than 1.1 (Minor)

### ISSUE THREAD

**Issue by dstufft** [mongrel2/mongrel2#235]
Mongrel2 may not want to fix this and that's OK, however I was reusing the HTTP parser code and I noticed that it rejects HTTP/1.x versions > 1.1 which runs counter to what the RFC intends.

_RFC 7230 Section 2.6 states:_

> The intention of HTTP's versioning design is that the major number will only be incremented if an incompatible message syntax is introduced, and that the minor number will only be incremented when changes made to the protocol have the effect of adding to the message semantics or implying additional capabilities of the sender. However, the minor version was not incremented for the changes introduced between [RFC2068] and [RFC2616], and this revision has specifically avoided any such changes to the protocol.
> 
> When an HTTP message is received with a major version number that the recipient implements, but a higher minor version number than what the recipient implements, the recipient SHOULD process the message as if it were in the highest minor version within that major version to which the recipient is conformant. A recipient can assume that a message with a higher minor version, when sent to a recipient that has not yet indicated support for that higher version, is sufficiently backwards-compatible to be safely processed by any implementation of the same major version.

I understand that it's unlikely that there will ever be a HTTP/1.2 so the difference is likely academic, however I figured I'd open this issue and if y'all want it I could submit a PR that would allow working with HTTP versions in the 1.x series other than 1.0 and 1.1.

**Comment by jasom** [comment]
Mongrel2's original design for oddball requests can be summed up with "[Postel](https://en.wikipedia.org/wiki/Robustness_principle) was wrong."  In keeping with that spirit, I don't see a reason at this time to support HTTP/1.X requests, particularly as HTTP/2 exists now.
