### ISSUE TITLE
Build tools/filters failed on Mac OS X 10.10.3 & XCode 6.3

### ISSUE THREAD

**Issue by holmescn** [mongrel2/mongrel2#262]
When build `mongrel2` with `XCode 6.3.2` command-line tools, tools/filters failed because of symbols not found. Some symbols comes from `zmq` and could be fixed by add `-lzmq` to `%.so` target in `tools/filters/Makefile`. But the leak of `_taskmain` symbols, I don't know how to fix it correctly. I have add `src/mongrel2.o` to the target, and it works, but I don't known whether it is correct or not.

I am using `brew` to install `zmq` and `sqlite3`. The other problem is that library path is not corrent. This could be fixed by either set the global `C_INCLUDE_PATH` and `LIBRARY_PATH` or use the `OPTFLAGS`. The `/usr/local/include` and `/usr/local/lib` should be in the finding path.

I think an empty `taskmain` function that is implemented in the filter could also solve the problem. but I have no idea about what it should be in the filters.

**Comment by jasom** [comment]
I use macports, and there is a build rule for that.  It ought to work with brew with just a few tweaks.

**Comment by holmescn** [comment]
@jasom I already figured out how to solved the compiling problem. But the last thing I am not sure is that do I do the right thing to solve the `taskmain` problem. Or I need to create an empty `taskmain` function in sendfile.c

**Comment by jasom** [comment]
I had to check my makefile, it' in there for the macports build rule; the option you need is `-undefined dynamic_lookup`
