### ISSUE TITLE
MessagePack

### ISSUE THREAD

**Issue by holmescn** [mongrel2/mongrel2#265]
I have read both TNetStrings and MessagePack definitions. I thougt that MessagePack protocol could also fit the needs of Mongrel2 internal usage. I know that TNetStrings is human readable, but it is meaningless when used as an internal message protocol. Just serialization and deserialization as quick as possible is helpful, in my opinion.

**Comment by jasom** [comment]
Maybe MessagePack is slightly better than TNS, maybe not.  MessagePack is more widely used, but TNS is much easier to implement.  I don't see enough of an advantage to add a 3rd serialization format to mongrel2
