### ISSUE TITLE
PolarSSL for 1.9.2

### ISSUE THREAD

**Issue by Funi1234** [mongrel2/mongrel2#277]
I saw the 1.9.2 release has a PolarSSL 1.3.10 patch file from 5 months ago.

Does that patch fix the following vulnerability: https://tls.mbed.org/tech-updates/security-advisories/polarssl-security-advisory-2014-04 ?

**Comment by jasom** [comment]
The intent was to pull PolarSSL 1.3.10 into 1.9.2, but somehow that didn't happen.  1.9.3 has the newest version (as does develop).
