### ISSUE TITLE
Build failed on OS X 10.11 beta

### ISSUE THREAD

**Issue by apjanke** [mongrel2/mongrel2#279]
The build is failing for me on OS X 10.11 Public Beta 6 with the Xcode 7 GM.

```
cc -g -O2 -Wall -Wextra -Isrc -Isrc/polarssl/include -pthread -rdynamic -DNDEBUG  -D_FILE_OFFSET_BITS=64 -fPIC    -c -o src/mem/halloc.o src/mem/halloc.c
clang: warning: argument unused during compilation: '-rdynamic'
In file included from src/mem/halloc.c:23:
src/mem/align.h:33:25: error: typedef redefinition with different types
      ('union max_align' vs 'long double')
typedef union max_align max_align_t;
                        ^
/Applications/Xcode-7-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/__stddef_max_align_t.h:32:21: note:
      previous definition is here
typedef long double max_align_t;
                    ^
1 error generated.
make: *** [src/mem/halloc.o] Error 1
```

Discovered this when testing the Homebrew formula on 10.11.
Full build logs: https://gist.github.com/apjanke/d6bca35c2dee11e04b8c

**Comment by jasom** [comment]
I think this is fixed in the develop branch, but I'm on my phone now so can't check

On September 14, 2015 3:09:06 AM PDT, Andrew Janke <notifications@github.com> wrote:
>The build is failing for me on OS X 10.11 Public Beta 6 with the Xcode
>7 GM.
>
>```
>cc -g -O2 -Wall -Wextra -Isrc -Isrc/polarssl/include -pthread -rdynamic
>-DNDEBUG  -D_FILE_OFFSET_BITS=64 -fPIC    -c -o src/mem/halloc.o
>src/mem/halloc.c
>clang: warning: argument unused during compilation: '-rdynamic'
>In file included from src/mem/halloc.c:23:
>src/mem/align.h:33:25: error: typedef redefinition with different types
>      ('union max_align' vs 'long double')
>typedef union max_align max_align_t;
>                        ^
>/Applications/Xcode-7-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/__stddef_max_align_t.h:32:21:
>note:
>      previous definition is here
>typedef long double max_align_t;
>                    ^
>1 error generated.
>make: *** [src/mem/halloc.o] Error 1
>```
>
>Discovered this when testing the Homebrew formula on 10.11.
>Full build logs: https://gist.github.com/apjanke/d6bca35c2dee11e04b8c
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mongrel2/mongrel2/issues/279

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by apjanke** [comment]
Yep, looks fixed. I built it from the `develop` branch on 10.11 GM seed and it worked.

```
# in mongrel2.rb
  devel do
    url "https://github.com/mongrel2/mongrel2.git", :branch => "develop"
    version "1.x-develop"
  end
```

```
$ brew install --devel --build-from-source mongrel2
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Cloning https://github.com/mongrel2/mongrel2.git
Updating /Library/Caches/Homebrew/mongrel2--git
==> Checking out branch develop
==> make all
==> make install PREFIX=/usr/local/Cellar/mongrel2/1.x-develop
🍺  /usr/local/Cellar/mongrel2/1.x-develop: 13 files, 2.6M, built in 24 seconds
```

Homebrew devs, would it be appropriate to add that `devel` clause in to the formula so other people can use it? Or is this a more obscure feature that should be reserved for particular use cases?

**Comment by cvortmann** [comment]
El Capitan is out now, would be great to have the changes in the dev branch readily available. :)

**Comment by apjanke** [comment]
I've put in a PR for the Homebrew formula to use `develop` for the `--HEAD` version: Homebrew/homebrew#44510.

**Comment by cvortmann** [comment]
Thanks!

**Comment by jkarneges** [comment]
Yep we're working on this. :) We'd meant to release a week ago but decided to fix a few more things first.
