### ISSUE TITLE
Reinstate DHE-RSA cipher-suites and use better default DH parameters

### ISSUE THREAD

**Issue by jcowgill** [mongrel2/mongrel2#295]
So I was looking over the TLS code and I noticed that all the DHE cipher-suites were disabled as a result of PR #254. Why? To my knowledge, DHE-RSA is one of the more secure key exchange algorithms (second only to the elliptic curve version) and is enabled by default in most applications I've seen. It's also one of only 3 key exchange algorithms deemed secure enough for TLS 1.3:
https://en.wikipedia.org/wiki/Transport_Layer_Security#Key_exchange_or_key_agreement

In the commits disabling these cipher-suites, it was mentioned that SSL Labs said they were insecure. I suspect that this was due to the use of 1024-bit DH paremeters rather than DHE itself being broken. Changing `ssl_default_dhm_P` and `ssl_default_dhm_G` to use one of the common DHE parameter sets >= 2048-bits from `polarssl/dhm.h` should be ok (after you've reinstated DHE-RSA).

**Comment by jcowgill** [comment]
@wysman

**Comment by wysman** [comment]
You are right.
Can you prepare a pull request with 4096 bit for DH ?

**Comment by jcowgill** [comment]
Ok, I'll see what I can do.

**Comment by jcowgill** [comment]
This is fixed now that #296 is merged.
