### ISSUE TITLE
Build failing on Ubuntu

### ISSUE THREAD

**Issue by saq7** [mongrel2/mongrel2#302]
I am trying to install mongrel2 on Ubuntu Precise. Following the directions listed here 

Mongrel2 version - 1.11.0 ZeroMQ version - 4.1.4

sudo make install fails with the following error

```
mongrel2 build/libm2.a -lzmq -ldl -lsqlite3 
build/libm2.a(fd.o): In function `mqrecv':
/home/vagrant/mongrel2/mongrel2/src/task/fd.c:283: undefined reference to `zmq_msg_recv'
/home/vagrant/mongrel2/mongrel2/src/task/fd.c:291: undefined reference to `zmq_msg_recv'
build/libm2.a(fd.o): In function `mqsend':
/home/vagrant/mongrel2/mongrel2/src/task/fd.c:303: undefined reference to `zmq_msg_send'
/home/vagrant/mongrel2/mongrel2/src/task/fd.c:311: undefined reference to `zmq_msg_send'
build/libm2.a(log.o): In function `Log_internal_thread':
/home/vagrant/mongrel2/mongrel2/src/log.c:94: undefined reference to `zmq_msg_recv'
build/libm2.a(log.o): In function `Log_poison_workers':
/home/vagrant/mongrel2/mongrel2/src/log.c:190: undefined reference to `zmq_msg_send'
build/libm2.a(log.o): In function `Log_request':
/home/vagrant/mongrel2/mongrel2/src/log.c:272: undefined reference to `zmq_msg_send'
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'bin/mongrel2' failed
make: *** [bin/mongrel2] Error 1
```

I tried this with the master of github, as well as with v1.11.0. Same error

**Comment by jasom** [comment]
I don't have a vm with Precise on it handy so I can't test this right away, but zeromq-4.1.4 is the version I'm currently using, so this should work.  Furthermore this function is clearly in zeromq-4.1: http://api.zeromq.org/4-1:zmq-msg-send

**Comment by jkarneges** [comment]
The libzmq package on Precise is version 2.1.11, so one theory is you've got libzmq-dev installed and it's taking precedence over your zeromq 4.1.4 install.

**Comment by saq7** [comment]
Still not sure what was causing this issue, but I ended up using trusty and didn't have the same problem. I am going to go ahead and close this issue.
