### ISSUE TITLE
Mongrel2 so not stop after sigterm (Debian stretch)

### ISSUE THREAD

**Issue by wysman** [mongrel2/mongrel2#315]
Hi,

I am running tests to prepare Debian jessie to stretch migration.
I have notice that a sigterm do not stop mongrel2 anymore.
It's look like the sigterm is really received and detected by mongrel2 because the log is populated, but the application do not stop.

Do you have some tips to help me ?

Best regards,

Here a extract from my log file :
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/server.c:365) Starting 0MQ with 1 threads.
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/request.c:60) MAX limits.header_count=1280
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/connection.c:1312) MAX limits.content_length=2097152000, limits.buffer_size=4096, limits.connection_stack_size=32768, limits.client_read_retries=5
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/connection.c:1318) MAX limits.proxy_read_retries=100, limits.proxy_read_retry_warn=10
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/task/fd.c:153) MAX limits.fdtask_stack=102400
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/handler.c:323) MAX allowing limits.handler_targets=128
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/handler.c:409) Binding handler PUSH socket tcp://127.0.0.1:12005 with identity: a2ac69ae-f5c9-11e6-b7bb-77cdd5c06696
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/handler.c:435) Binding listener SUB socket tcp://127.0.0.1:12004 subscribed to: 
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/handler.c:323) MAX allowing limits.handler_targets=128
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/handler.c:409) Binding handler PUSH socket tcp://127.0.0.1:12001 with identity: 6ac3b5a0-b4e8-11e6-b4b6-1b16a42ff0ac
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/handler.c:435) Binding listener SUB socket tcp://127.0.0.1:12000 subscribed to: 
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/handler.c:323) MAX allowing limits.handler_targets=128
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/handler.c:409) Binding handler PUSH socket tcp://127.0.0.1:12009 with identity: 34ab7c8c-f881-11e6-8b02-7f27225f795b
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/handler.c:435) Binding listener SUB socket tcp://127.0.0.1:12008 subscribed to: 
> Fri, 19 May 2017 12:25:45 GMT [INFO] (src/control.c:437) Setting up control socket in at tcp://127.0.0.1:9999
> Fri, 19 May 2017 12:25:46 GMT [INFO] (src/mongrel2.c:301) -- Mongrel2/1.11.0 Running. Copyright (C) Zed A. Shaw. Licensed BSD.
> Fri, 19 May 2017 12:25:54 GMT [INFO] (src/mongrel2.c:96) SHUTDOWN REQUESTED: MURDER
> Fri, 19 May 2017 12:25:57 GMT [INFO] (src/mongrel2.c:92) SIGINT CAUGHT AGAIN, ASSUMING MURDER.
> Fri, 19 May 2017 12:26:02 GMT [INFO] (src/mongrel2.c:92) SIGINT CAUGHT AGAIN, ASSUMING MURDER.
> 

My config file : 

> static_acme = Dir(
>     base            = '/xxx/acme/.well-known/acme-challenge/',
>     index_file      = 'index.html',
>     default_ctype   = 'text/plain'
> )
> 
> http = Server(
>     name="http",
>     uuid="74d3a7cb-63af-4bb2-bdbb-e41bbf860865",
>     port=80,
>     pid_file="/var/run/mongrel2-http.pid",
>     access_log="/var/log/mongrel2-http-acccess.log",
>     error_log="/var/log/mongrel2-http-error.log",
>     default_host="yyy.power-lan.com",
>     hosts = [
> Host(name="xxx.power-lan.com",
>     routes={
>         '/': Dir(
>             base            = '/var/www/',
>             index_file      = 'index.html',
>             default_ctype   = 'text/plain'
>         ),
>         '/.well-known/acme-challenge/': static_acme
>     }
> )
> Host(name="zzz.power-lan.com",
>     routes={
>         '/': Handler(
>             send_spec	=	'tcp://127.0.0.1:12005',
>             send_ident	=	'a2ac69ae-f5c9-11e6-b7bb-77cdd6c06696',
>             recv_spec	=	'tcp://127.0.0.1:12004',
>             recv_ident	=	''
>         ),
>         '/.well-known/acme-challenge': static_acme
>     }
> )
> 
> ... Many hosts ...
> ]
> )
> 
> settings = {
>     "limits.content_length": 2097152000,
>     "upload.temp_store": "tmp/mongrel2.upload.XXXXXX",
>     "control_port" : "tcp://127.0.0.1:9999"
> }
> 	
> servers = [http]
> 
>

**Comment by jasom** [comment]
Hi William,

Sorry to let this languish so long; is this from .deb packages or built from source?

**Comment by wysman** [comment]
Hi,

I have test from debian package.

Today, I update the debian stretch and the issue is not here anymore, but the mongrel2 package was not updated... Maybe the issue is in a linked library (tls). 

Best regards,
