### ISSUE TITLE
Mongrel2 do not close connection when requested after a first payload

### ISSUE THREAD

**Issue by wysman** [mongrel2/mongrel2#322]
Hi,

I try to update some php code to ensure that the HTTP connection is closed when the user ask it with the HTTP/1.1 headers (Connection : close)

I try on the Debian stretch version (1.11.0) and the develop branch (commit 4d67a3a1c524dbc08726d7af353cf9c1d8fc6fbd), i have the same results on both.

When i want to close the connection without answer, it's works fine. I am using the following payload.

> string(42) "da530a7c-fadf-11e7-8c60-ab6c38b7f534 1:5, "

But, when i want to close the connection after push an answer, the close message do not works.
The connection stay open, and the http client reach the timeout.

> string(177) "da530a7c-fadf-11e7-8c60-ab6c38b7f534 1:3, HTTP/1.1 200 OK
> Content-Type: text/html; charset=utf-8
> X-Powered-By: Photon - http://photon-project.com
> Content-Length: 7
> 
> PWLN-OK"

follow by 

> string(42) "da530a7c-fadf-11e7-8c60-ab6c38b7f534 1:3, "

In the compiled version of mongrel2, i have check that the empty payload is received.

>     log_info("handler_process_request, blength(payload) = %d", blength(payload));

and the payload size are correct

> [INFO] (src/handler.c:295) handler_process_request, blength(payload) = 135
> [INFO] (src/handler.c:295) handler_process_request, blength(payload) = 0

**Comment by jkarneges** [comment]
Closing the connection after sending a response works for me with version 4d67a3a.

**Comment by wysman** [comment]
@jkarneges can you share the content of your two zmq message, and your m2 config ? I want to reproduce a working case on my laptop. Thx

**Comment by wysman** [comment]
Hi,

After various tests, i found that the connection is keep open by a proxy server (the mongrel2 proxy handler) and not by the mongrel2 with the zmq handler and the application.

Thanks

**Comment by jkarneges** [comment]
Ah good, thanks for testing!
