### ISSUE TITLE
make fails with fatal error: sqlite3.h: No such file or directory compilation terminated. 

### ISSUE THREAD

**Issue by kracekumar** [mongrel2/mongrel2#86]
I cloned the mongrel2 and ran `make` command and finally ended in following error.

kracekumar@python-lover:~/codes/python/mongrel2$ make
cc -g -O2 -Wall -Wextra -Isrc -pthread -rdynamic -DNDEBUG  -D_FILE_OFFSET_BITS=64 -fPIC    -c -o src/config/config.o src/config/config.c
src/config/config.c:42:21: fatal error: sqlite3.h: No such file or directory
compilation terminated.
make: **\* [src/config/config.o] Error 1

I looked into the src/config/config.c at line no 42 there is a header inclusion as follows `#include <sqlite3.h>`, I grepped for sqlite3.h but I couldn't find it.

Note: I have installed sqlite3 already in my system so I commented and tried installation found in many places sqlite3 is required.

**Comment by acooper267** [comment]
when I run yum install ruby-devel sqlite sqlite-devel ruby-rdoc
I get the following:

Error: Package: ruby-devel-2.0.0.648-30.el7.x86_64 (base)
           Requires: ruby(x86-64) = 2.0.0.648-30.el7
           Installed: ruby-2.2.3-1.el7.centos.x86_64 (installed)
               ruby(x86-64) = 2.2.3-1.el7.centos
           Available: ruby-2.0.0.648-30.el7.x86_64 (base)
               ruby(x86-64) = 2.0.0.648-30.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by jasom** [comment]
mongrel2 doesn't require ruby, try the yum command without it?

**Comment by DireStraits01** [comment]
> @daltonmatos @jsimmons : Thanks you both are right, I didn't have sqlite3-dev package. It was under ubuntu, I fixed it by`sudo apt-get install libsqlite3-dev`, I think we should add this in documentation.

thank you dude

**Comment by shivendra04** [comment]
> yum install sqlite-devel.x86_64

It worked for me
